version: 2

jobs:
    build:
        docker:            
            - image: thomasweise/texlive
        steps:
            - checkout
            - run:
                name: Greeting
                command: echo Hello, world.
            - run:
                name: Print the Current Time
                command: date
