version: 2

jobs:
    build:
        docker:
            - image: thomasweise/texlive
        branches:
            only:
                - master
        steps:
            - checkout
            - run:
                name: Compile PDF with Makefile
                command: |
                    make ci-info
                    make cv
                    make cover-letter
                    make clean-aux
            - store_artifacts:
                path: ~/project/build
